#!/usr/bin/env node
/**
 * Generates the router stub for every character and system page from
 * data/navigation.json.
 *
 * Each stub is a ~40-line file that sets window.PAGE_ROUTE and loads
 * js/page_router.js; all the real markup lives in that module. Before v0.9
 * these were 23 + 12 hand-maintained ~160-line files that differed only in a
 * page id and a title, which is exactly the shape of thing that drifts.
 *
 * Deliberately offline: this reads navigation.json, not the database. R4
 * makes navigation.json itself a generated artifact (from the site_pages
 * table); this script stays the last step of that pipeline either way, so it
 * has one input and one job.
 *
 * Usage:
 *   node scripts/generate-pages.js            # report only (same as --check)
 *   node scripts/generate-pages.js --check    # exit 1 if any file is stale
 *   node scripts/generate-pages.js --write    # write the files
 *   node scripts/generate-pages.js --write --adopt
 *       # additionally take ownership of existing files that predate the
 *       # GENERATED marker. Needed exactly once, when converting
 *       # hand-authored pages. Never use it in CI: it disables the guard
 *       # that stops this script eating a hand-written page.
 *
 * Safety rules, in order of how badly each would hurt if it were missing:
 *   1. NEVER_TOUCH - hand-authored pages that merely look routable.
 *   2. Marker check - refuses to overwrite any file lacking the GENERATED
 *      marker, so even if NEVER_TOUCH is wrong a hand-written page survives.
 *   3. Refuse on empty - an empty page set means a broken input, not a
 *      request to delete every page.
 *   4. No partial writes - everything is built and validated in memory
 *      first; a failure writes nothing at all.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const MARKER = '<!-- GENERATED by scripts/generate-pages.js - do not edit by hand -->';

// Social/SEO metadata has to be in the served HTML, not injected at runtime:
// Discord, Twitter and Facebook unfurlers do not execute JavaScript, so tags
// added by js/site_meta.js would never be seen by any of them. That is the
// whole reason these live in the generator.
//
// Absolute, because og:image and og:url are meaningless as relative paths -
// the unfurler has no page context to resolve them against.
const SITE_ORIGIN = 'https://dogslamloop.com';  // matches CNAME
const SITE_NAME = 'Dogslamloop Wiki';
const DEFAULT_OG_IMAGE = `${SITE_ORIGIN}/medias/images/DogslamloopIconGay.webp`;

// `summary` rather than `summary_large_image`: the site logo is ~194x134, and
// claiming a large banner for a small image renders as an ugly upscale.
// Revisit when per-page images (e.g. character portraits) are available.
const TWITTER_CARD = 'summary';

// Escapes for an HTML attribute value. Page names are owner-authored, but a
// stray apostrophe or ampersand in a name would otherwise break the tag.
function attr(value) {
    return String(value === null || value === undefined ? '' : value)
        .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function describe(name, pageType) {
    return pageType === 'character'
        ? `Frame data, matchups, and strategy for ${name} in Jujutsu Shenanigans.`
        : `A Jujutsu Shenanigans guide to ${name}, on the Dogslamloop wiki.`;
}

function socialTags({ name, relPath, pageType, image }) {
    const url = `${SITE_ORIGIN}/${relPath}`;
    const description = describe(name, pageType);

    // A character's own portrait makes a far more useful Discord preview than
    // the site logo repeated 22 times. Portraits come from
    // data/page-previews.json, refreshed from Supabase by
    // scripts/fetch-previews.js - read here as a committed file so this
    // generator stays offline and its --check stays deterministic.
    //
    // System pages and any character without a portrait fall back to the
    // logo: emitting no og:image at all, or a broken one, is worse than a
    // generic image.
    const ogImage = image || DEFAULT_OG_IMAGE;

    // summary_large_image only for real portraits. The site logo is ~194x134
    // and upscales badly into a banner, so logo-backed pages keep the compact
    // card.
    const card = image ? 'summary_large_image' : TWITTER_CARD;

    return `    <meta name="description" content="${attr(description)}">
    <link rel="canonical" href="${attr(url)}">

    <meta property="og:site_name" content="${attr(SITE_NAME)}">
    <meta property="og:type" content="article">
    <meta property="og:title" content="${attr(name)}">
    <meta property="og:description" content="${attr(description)}">
    <meta property="og:url" content="${attr(url)}">
    <meta property="og:image" content="${attr(ogImage)}">
    <meta name="twitter:card" content="${card}">`;
}

// Pages that live under characters/ or systems/ but are hand-authored and
// must never be produced (or clobbered) by this script.
//   Template     - documentation page in a character page's clothes, 5 tabs
//   collaborators- own fetch engine and containers
//   tierlist     - own pageType, loads tierlist.js
//   updatelog    - driven by home_widgets.js
//   color-codes  - hand-authored swatch markup
const NEVER_TOUCH = new Set([
    'characters/Template/index.html',
    'systems/collaborators/index.html',
    'systems/tierlist/index.html',
    'systems/updatelog/index.html',
    'systems/color-codes/index.html',
    'characters/index.html',
    'systems/index.html',
]);

function characterStub({ pageId, title, docTitle, social }) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    ${MARKER}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${docTitle}</title>
    <link rel="icon" type="image/jpg" href="../../medias/images/DogslamloopIconGay.webp">

${social}

    <link rel="stylesheet" href="../../style/Common.css">
    <link rel="stylesheet" href="../../style/ColorCoding.css">

    <link rel="stylesheet" href="../../style/Buttons.css">
    <link rel="stylesheet" href="../../style/Modals.css">
    <link rel="stylesheet" href="../../style/Forms.css">
    <link rel="stylesheet" href="../../style/Badges.css">
    <link rel="stylesheet" href="../../style/Alerts.css">
    <link rel="stylesheet" href="../../style/Cards.css">
    <link rel="stylesheet" href="../../style/FrameData.css">

    <link rel="stylesheet" href="../../style/Layout.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"></script>

    <script>window.PAGE_ROUTE = { pageId: "${pageId}", pageType: "character", title: "${title}" };</script>
</head>
<body class="site-body p-0">

    <script src="../../js/page_router.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>

    <script src="../../js/site_utils.js"></script>
    <script src="../../js/site_meta.js"></script>
    <script src="../../js/pagebuilder.js"></script>
    <script src="../../js/framedata.js"></script>
    <script src="../../js/description.js"></script>
    <script src="../../js/internalstyling.js"></script>

    <script src="../../js/page_boot.js"></script>
</body>
</html>
`;
}

function systemStub({ pageId, title, docTitle, social }) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    ${MARKER}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${docTitle}</title>
    <link rel="icon" type="image/jpg" href="../../medias/images/DogslamloopIconGay.webp">

${social}

    <link rel="stylesheet" href="../../style/Common.css">
    <link rel="stylesheet" href="../../style/Layout.css">
    <link rel="stylesheet" href="../../style/Cards.css">
    <link rel="stylesheet" href="../../style/Buttons.css">
    <link rel="stylesheet" href="../../style/Badges.css">
    <link rel="stylesheet" href="../../style/ColorCoding.css">
    <link rel="stylesheet" href="../../style/Alerts.css">
    <link rel="stylesheet" href="../../style/Modals.css">

    <script>window.PAGE_ROUTE = { pageId: "${pageId}", pageType: "system", title: "${title}" };</script>
</head>
<body class="site-body p-0">

    <script src="../../js/page_router.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>
    <script src="../../js/site_utils.js"></script>
    <script src="../../js/site_meta.js"></script>
    <script src="../../js/pagebuilder.js"></script>
    <script src="../../js/description.js"></script>

    <script src="../../js/page_boot.js"></script>
</body>
</html>
`;
}

// A page's <title> suffix differs by type, matching what the hand-authored
// files used: characters said "| Dogslamloop", system pages said
// "| Dogslamloop Wiki". Preserved rather than unified, so this script's output
// matches the committed files byte-for-byte and the diff stays reviewable.
function docTitleFor(name, pageType) {
    return pageType === 'character' ? `${name} | Dogslamloop` : `${name} | Dogslamloop Wiki`;
}

/**
 * Turn navigation.json into the full set of files to write.
 * Pure: builds everything in memory, touches no disk.
 */
function buildPages(nav, previews = {}) {
    const pages = [];
    const problems = [];

    for (const [category, entries] of Object.entries(nav)) {
        if (!Array.isArray(entries)) continue;

        for (const entry of entries) {
            const cms = entry.cms_config;
            if (!cms) continue;
            if (cms.pageType !== 'character' && cms.pageType !== 'system') continue;
            if (!entry.url) continue;

            // Normalize to forward slashes; navigation.json is the authority
            // for where a page lives, including its folder capitalization.
            const relPath = entry.url.replace(/\\/g, '/');
            if (NEVER_TOUCH.has(relPath)) continue;

            if (!/^(characters|systems)\/[^/]+\/index\.html$/.test(relPath)) {
                problems.push(`${category}: "${relPath}" is not a two-level page path; refusing to generate it.`);
                continue;
            }

            const social = socialTags({
                name: entry.name,
                relPath,
                pageType: cms.pageType,
                image: previews[cms.pageId],
            });
            const html = cms.pageType === 'character'
                ? characterStub({ pageId: cms.pageId, title: entry.name, docTitle: docTitleFor(entry.name, 'character'), social })
                : systemStub({ pageId: cms.pageId, title: entry.name, docTitle: docTitleFor(entry.name, 'system'), social });

            pages.push({ relPath, html, pageId: cms.pageId, pageType: cms.pageType });
        }
    }

    return { pages, problems };
}

function main() {
    const args = process.argv.slice(2);
    const write = args.includes('--write');
    const adopt = args.includes('--adopt');

    const navPath = path.join(ROOT, 'data', 'navigation.json');
    const nav = JSON.parse(fs.readFileSync(navPath, 'utf8'));

    // Optional: pages simply fall back to the site logo if it is absent, so a
    // fresh clone or a failed fetch degrades to v0.9's behaviour rather than
    // breaking generation.
    const previewsPath = path.join(ROOT, 'data', 'page-previews.json');
    const previews = fs.existsSync(previewsPath)
        ? JSON.parse(fs.readFileSync(previewsPath, 'utf8'))
        : {};

    const { pages, problems } = buildPages(nav, previews);

    if (problems.length > 0) {
        console.error('generate-pages FAILED - refusing to write:\n');
        problems.forEach(p => console.error(`  - ${p}`));
        process.exit(1);
    }

    // An empty set means the input is broken, not that every page should be
    // deleted. This is the guard that matters most once the input comes from
    // a network call in R4.
    if (pages.length === 0) {
        console.error('generate-pages FAILED - refusing to regenerate from an empty page set.');
        process.exit(1);
    }

    const stale = [];
    const blocked = [];

    for (const page of pages) {
        const abs = path.join(ROOT, page.relPath);
        const exists = fs.existsSync(abs);
        const current = exists ? fs.readFileSync(abs, 'utf8') : null;

        // Second line of defence behind NEVER_TOUCH: never overwrite a file
        // that was not produced by this script. --adopt is the deliberate,
        // one-time override used when converting hand-authored pages.
        if (exists && !current.includes(MARKER) && !adopt) {
            blocked.push(page.relPath);
            continue;
        }

        if (current !== page.html) stale.push(page);
    }

    if (blocked.length > 0) {
        console.error('generate-pages FAILED - these files exist but carry no GENERATED marker:\n');
        blocked.forEach(p => console.error(`  - ${p}`));
        console.error('\nThey look hand-authored. Add them to NEVER_TOUCH, or delete them if they really should be generated.');
        process.exit(1);
    }

    if (!write) {
        if (stale.length === 0) {
            console.log(`generate-pages --check passed (${pages.length} pages up to date).`);
            return;
        }
        console.error(`generate-pages --check FAILED - ${stale.length} of ${pages.length} page(s) are stale:\n`);
        stale.forEach(p => console.error(`  - ${p.relPath}`));
        console.error('\nRun: node scripts/generate-pages.js --write');
        process.exit(1);
    }

    for (const page of stale) {
        const abs = path.join(ROOT, page.relPath);
        fs.mkdirSync(path.dirname(abs), { recursive: true });
        fs.writeFileSync(abs, page.html);
        console.log(`  wrote ${page.relPath}`);
    }
    console.log(stale.length === 0
        ? `generate-pages: nothing to do (${pages.length} pages already current).`
        : `generate-pages: wrote ${stale.length} of ${pages.length} page(s).`);
}

if (require.main === module) main();

module.exports = { buildPages, MARKER, NEVER_TOUCH };
