#!/usr/bin/env node
/**
 * Generates sitemap.xml from data/navigation.json.
 *
 * Deliberately offline and deterministic, for the same reason
 * generate-pages.js is: CI compares the committed file byte-for-byte, so this
 * must produce identical output from identical input on every machine. That
 * rules out anything time-based.
 *
 * In particular there is no <lastmod>. The honest source for it would be
 * site_pages.updated_at, which is a network read this script does not do, and
 * a build timestamp would mark every page as changed on every run - which is
 * exactly the signal <lastmod> exists to avoid sending. Google ignores
 * <changefreq> and <priority> outright, so those are omitted too rather than
 * emitted as decoration.
 *
 * Usage:
 *   node scripts/generate-sitemap.js            # report only (same as --check)
 *   node scripts/generate-sitemap.js --check    # exit 1 if sitemap.xml is stale
 *   node scripts/generate-sitemap.js --write    # write sitemap.xml
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SITEMAP_PATH = path.join(ROOT, 'sitemap.xml');

// Matches CNAME and generate-pages.js. A sitemap must list absolute URLs on
// the same host as the sitemap itself, or crawlers reject the entries.
const SITE_ORIGIN = 'https://dogslamloop.com';

// The homepage is not in navigation.json - nothing navigates "to" it, it is
// where navigation starts - so it is added explicitly.
const EXTRA_PATHS = [
    '',                      // the site root
    'privacy-policy.html',
];

// Staff tools and authoring pages. Kept in sync with robots.txt by the test in
// tests/sitemap.spec.js, which asserts nothing disallowed there appears here -
// listing a page in the sitemap while disallowing it in robots.txt is a
// contradictory signal that Search Console reports as an error.
const EXCLUDED = new Set([
    'admin.html',
    'owner.html',
    'edit.html',
    'post-editor.html',
    'submissions.html',
    'history.html',
    '404.html',
]);

function xmlEscape(value) {
    return String(value)
        .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

/**
 * Pure: navigation object in, sitemap XML string out.
 *
 * Exported so the round-trip test can assert against it without touching the
 * filesystem, matching fetch-registry.js's buildNavigation.
 */
function buildSitemap(nav, extraPaths = EXTRA_PATHS) {
    const seen = new Set();
    const paths = [];

    const add = (relPath) => {
        // External links (the GitHub repo) belong to another host; a sitemap
        // may only list URLs on its own origin.
        if (/^https?:\/\//i.test(relPath)) return;
        const clean = relPath.replace(/\\/g, '/').replace(/^\.?\//, '');
        if (EXCLUDED.has(clean)) return;
        if (seen.has(clean)) return;
        seen.add(clean);
        paths.push(clean);
    };

    extraPaths.forEach(add);

    for (const entries of Object.values(nav)) {
        if (!Array.isArray(entries)) continue;
        for (const entry of entries) {
            if (!entry || !entry.url) continue;
            // Archived and draft pages never reach navigation.json
            // (fetch-registry.js drops them), so a tombstone cannot be
            // advertised here - which is the behaviour we want.
            add(entry.url);
        }
    }

    const urls = paths
        .map(p => `  <url>\n    <loc>${xmlEscape(`${SITE_ORIGIN}/${p}`)}</loc>\n  </url>`)
        .join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/generate-sitemap.js - do not edit by hand -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function main() {
    const write = process.argv.includes('--write');

    const nav = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'navigation.json'), 'utf8'));
    const next = buildSitemap(nav);

    // An empty result means navigation.json is broken, not that the site has
    // no pages. Same guard as generate-pages.js, for the same reason.
    const urlCount = (next.match(/<url>/g) || []).length;
    if (urlCount <= EXTRA_PATHS.length) {
        console.error('generate-sitemap FAILED - refusing to write a sitemap with no pages in it.');
        process.exit(1);
    }

    const current = fs.existsSync(SITEMAP_PATH) ? fs.readFileSync(SITEMAP_PATH, 'utf8') : null;

    if (current === next) {
        console.log(`generate-sitemap: up to date (${urlCount} URLs).`);
        return;
    }

    if (!write) {
        console.error('generate-sitemap --check FAILED - sitemap.xml is stale.');
        console.error('\nRun: node scripts/generate-sitemap.js --write');
        process.exit(1);
    }

    fs.writeFileSync(SITEMAP_PATH, next);
    console.log(`generate-sitemap: wrote sitemap.xml (${urlCount} URLs).`);
}

if (require.main === module) main();

module.exports = { buildSitemap, EXCLUDED, EXTRA_PATHS, SITE_ORIGIN };
