#!/usr/bin/env node
/**
 * Stamps a content hash onto js/site_utils.js in every page's <script src>.
 *
 * The bug this exists for, 2026-08-10: GitHub Pages serves js/ with
 * max-age=3600. A deploy that adds a new module depending on a new shared
 * helper therefore gives the browser a *fresh* copy of the new file and an
 * *hour-old* copy of site_utils.js. The new file called a helper the cached
 * copy did not have, the TypeError went straight through edit.html's boot
 * try/catch, and the editor was dead for every contributor who had the site
 * open - reported on the live site within minutes of the merge.
 *
 * A query string on the URL makes it a different cache key, so the moment the
 * hash changes every browser fetches the new file. site_utils.js is the only
 * file stamped because it is the only genuinely shared module: everything else
 * is loaded by the page that owns it, and a page and its own script are always
 * deployed together.
 *
 * Generated stubs are stamped by scripts/generate-pages.js itself, from the
 * same helper, so `generate-pages --check` and this script agree. This script
 * only rewrites the hand-authored pages.
 *
 * Usage:
 *   node scripts/stamp-assets.js            # report only (same as --check)
 *   node scripts/stamp-assets.js --check    # exit 1 if any page is stale
 *   node scripts/stamp-assets.js --write    # write the files
 */

const fs = require('fs');
const path = require('path');
const { siteUtilsVersion, stampSiteUtils } = require('./asset-version.js');

const ROOT = path.join(__dirname, '..');

// Every .html that is not a generated stub. Generated stubs live exactly two
// levels down under a page directory and carry the generator's marker, so
// excluding them by marker rather than by path keeps the two scripts from
// disagreeing about which files they each own.
const GENERATED_MARKER = 'GENERATED by scripts/generate-pages.js';

function collectHtml(dir, out = []) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        if (entry.name === 'node_modules' || entry.name === '.git' || entry.name === 'test-results') continue;
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) collectHtml(full, out);
        else if (entry.isFile() && entry.name.endsWith('.html')) out.push(full);
    }
    return out;
}

function main() {
    const write = process.argv.includes('--write');
    const version = siteUtilsVersion();

    const stale = [];
    let checked = 0;

    for (const file of collectHtml(ROOT)) {
        const before = fs.readFileSync(file, 'utf8');
        if (before.includes(GENERATED_MARKER)) continue;
        if (!/src="[^"]*js\/site_utils\.js/.test(before)) continue;

        checked++;
        const after = stampSiteUtils(before, version);
        if (after === before) continue;

        stale.push(path.relative(ROOT, file).replace(/\\/g, '/'));
        if (write) fs.writeFileSync(file, after);
    }

    const label = `stamp-assets: site_utils.js v${version}`;

    if (stale.length === 0) {
        console.log(`${label} - up to date (${checked} hand-authored page(s)).`);
        return;
    }

    if (write) {
        stale.forEach(f => console.log(`  stamped ${f}`));
        console.log(`${label} - stamped ${stale.length} of ${checked} page(s).`);
        return;
    }

    stale.forEach(f => console.log(`  STALE ${f}`));
    console.error(`${label} - ${stale.length} page(s) carry an old or missing version. Run: npm run generate`);
    process.exit(1);
}

if (require.main === module) main();

module.exports = { collectHtml };
