-- Prereq for gen_random_uuid() if not already installed
create extension if not exists pgcrypto with schema extensions;

-- 1) public.page_data
create table if not exists public.page_data (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  page_id text null,
  desc_data jsonb null,
  frame_data jsonb null,
  page_type text null default 'character'::text,
  constraint character_data_pkey primary key (id),
  constraint character_data_character_id_key unique (page_id),
  constraint character_id_unique unique (page_id)
);

alter table public.page_data enable row level security;

create policy "Admin Write Live Data"
on public.page_data
as permissive
for all
to authenticated
using ((get_my_role() = any (array['admin'::text, 'reviewer'::text])))
with check ((get_my_role() = any (array['admin'::text, 'reviewer'::text])));

create policy "Public Read Live Data"
on public.page_data
as permissive
for select
to public
using (true);

-- 2) public.pending_revisions
create table if not exists public.pending_revisions (
  id uuid not null default gen_random_uuid(),
  page_id text not null,
  desc_data jsonb null,
  frame_data jsonb null,
  author_id uuid not null,
  author_name text null,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  status text null default 'pending'::text,
  supporters uuid[] null default '{}'::uuid[],
  ticket_chat jsonb null default '[]'::jsonb,
  opposers uuid[] null default '{}'::uuid[],
  qa_metadata jsonb null default '{}'::jsonb,
  page_type text null default 'character'::text,
  target_scope text null,
  target_key text null,
  is_delta boolean null default false,
  delta_payload jsonb null,
  constraint pending_revisions_pkey primary key (id),
  constraint pending_revisions_author_id_fkey
    foreign key (author_id) references auth.users(id)
);

alter table public.pending_revisions enable row level security;

create policy "Guests can submit revisions"
on public.pending_revisions
as permissive
for insert
to authenticated
with check ((auth.uid() = author_id));

create policy "Staff can manage queue"
on public.pending_revisions
as permissive
for all
to public
using ((get_my_role() = any (array['admin'::text, 'reviewer'::text])));

create policy "Staff can view queue"
on public.pending_revisions
as permissive
for select
to public
using ((get_my_role() = any (array['admin'::text, 'reviewer'::text])));

-- 3) public.user_roles
create table if not exists public.user_roles (
  user_id uuid not null,
  role text not null,
  constraint user_roles_pkey primary key (user_id, role),
  constraint user_roles_role_check
    check ((role = any (array['admin'::text, 'reviewer'::text, 'trusted_editor'::text, 'contributor'::text, 'viewer'::text]))),
  constraint user_roles_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade
);

alter table public.user_roles enable row level security;

create policy "Users can read own role"
on public.user_roles
as permissive
for select
to public
using ((auth.uid() = user_id));

-- 4) public.user_notifications
create table if not exists public.user_notifications (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone null default now(),
  user_id uuid not null,
  message text not null,
  link text null,
  is_read boolean null default false,
  constraint user_notifications_pkey primary key (id),
  constraint user_notifications_user_id_fkey
    foreign key (user_id) references auth.users(id)
);

alter table public.user_notifications enable row level security;

create policy "Staff insert notifications"
on public.user_notifications
as permissive
for insert
to authenticated
with check ((get_my_role() = any (array['admin'::text, 'reviewer'::text])));

create policy "Users delete own notifications"
on public.user_notifications
as permissive
for delete
to authenticated
using ((auth.uid() = user_id));

create policy "Users read own notifications"
on public.user_notifications
as permissive
for select
to authenticated
using ((auth.uid() = user_id));

-- 5) public.page_history
create table if not exists public.page_history (
  id uuid not null default gen_random_uuid(),
  page_id text not null,
  desc_data jsonb not null,
  frame_data jsonb not null,
  updated_by_user text null,
  version_timestamp timestamp with time zone null default now(),
  page_type text null,
  constraint page_history_pkey primary key (id)
);

alter table public.page_history enable row level security;
-- No RLS policies currently exist on public.page_history